name: Build and deploy with Nikola
on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build and deploy website to gh-pages'
    steps:
    - name: Install sass
      run: sudo gem install sass
    - name: Check out
      uses: actions/checkout@v3
    - name: Run Nikola action
      uses: getnikola/nikola-action@v8
