name: Build Ansible community site
on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        repository: oraNod/community-website
        ref: main
    - name: Show me
      run: ls -la
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8

